### ISSUE TITLE
Popup should not close on file navigation initiated by the popup

### ISSUE THREAD

**Issue by AidanWelch** [hober/web-extensions#325] opened 2022-11-15 23:30 UTC
Presently, if trying to either saveAs or input a file to a browser extension you have to create a separate tab, and it cannot be done in popup.  Clicking within the file navigation initiated by the popup should not close the popup, allowing the popup script to actually be used for file inputting and outputting.

This does slightly expose a risk of a malicious popup spamming file navigation popups, but that doesn't justify removing the functionality entirely.  This change would improve both user and developer experience.

**Comment by AidanWelch** [comment] 2022-11-16 16:55
On further testing, Chrome actually does behave this way, but Firefox does not.

**Comment by hanguokai** [comment] 2022-11-16 18:35
Hi @AidanWelch 

It looks like a Chrome bug. There was a [discussion](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/aZH3sUbLU9g/m/ctAddRPaAAAJ) and a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1158230) for it. But it seems to have been fixed. I can't reproduce this problem in a simple example. If you can, please [file a bug](https://crbug.com/new) and close this issue (because browser-specific bugs are not discussed here).

**Comment by AidanWelch** [comment] 2022-11-16 18:37
> Hi @AidanWelch
> 
> It looks like a Chrome bug. There was a [discussion](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/aZH3sUbLU9g/m/ctAddRPaAAAJ) and a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1158230) for it. But it seems to have been fixed. I can't reproduce this problem in a simple example. If you can, please [file a bug](https://crbug.com/new) and close this issue (because browser-specific bugs are not discussed here).

The issue doesn't occur on Chrome, and as far as I know it isn't an intended feature of Firefox as it doesn't happen in Firefox.  I think it is instead an asynchrony in the standard.  (Chrome behaves how I described, Firefox doesn't)

**Comment by hanguokai** [comment] 2022-11-16 18:47
> Chrome behaves how I described, Firefox doesn't

Do you means it works on Chrome but doesn't work on Firefox? Then it is a Firefox bug. Normally, using `<input type=file>` or download action in the popup should not cause the popup to be closed.

**Comment by AidanWelch** [comment] 2022-11-16 19:25
> Do you means it works on Chrome but doesn't work on Firefox? 

Yeah

> Then it is a Firefox bug. Normally, using `<input type=file>` or download action in the popup should not cause the popup to be closed.

Oh okay, I understand.  I thought it was intended in Firefox.

**Comment by Sxderp** [comment] 2022-11-16 20:07
There are some existing, old, bugs for Firefox.
https://bugzilla.mozilla.org/show_bug.cgi?id=1292701
https://bugzilla.mozilla.org/show_bug.cgi?id=1366330
https://bugzilla.mozilla.org/show_bug.cgi?id=1411000 [tangential]

**Closed as not planned** 2023-05-22 13:56 UTC
Labels: inconsistency, follow-up: firefox
