### ISSUE TITLE
Agenda discussion for public meeting on 2024-02-15

### ISSUE THREAD

**Issue by Rob--W** [hober/web-extensions#535] opened 2024-02-01 17:39 UTC
This issue is used to collect topic suggestions for our February 15, 2024 meeting. We will stop accepting suggestions ~48 hours before the meeting and the final agenda will be added to the [meeting notes doc](https://docs.google.com/document/d/1QkwhEMtMS67JBUkl_WVPZ4lRSKoWcQNlLJSf_GwSXg8/edit) ~24 hours before the meeting.

The content below this line will be copy-pasted to the agenda section of the meeting.

---

The meeting will start at 3 minutes after the hour.
See [issue 531](https://github.com/w3c/webextensions/issues/531) for an explanation of this agenda format.

 * **Announcements** (2 minutes)
 * **Triage** (15 minutes)
   * (nominated issues here)
* **Timely issues** (10 minutes)
   * (nominated issues here)
 * **Check-in on existing issues** (20 minutes)
   * (nominated issues here)

**Comment by Rob--W** [comment] 2024-02-01 17:45
The following issues were part of the previous meeting's agenda but haven't been discussed. Due to the huge list if would be nice if we can cover most of them async and discuss the remaining ones in the meeting:
   * [Follow up](https://github.com/w3c/webextensions/issues/402#issuecomment-1591619962) on [Issue 402](https://github.com/w3c/webextensions/issues/402): Provide a mean to discriminate initiators and destinations belonging to a local (private) network
   * [Issue 454](https://github.com/w3c/webextensions/issues/454): Add a new manifest key to include a origin trial token (anton?)
   * [Issue 519](https://github.com/w3c/webextensions/issues/519): Proposal: Event.addListener should accept an interface.
   * [Issue 517](https://github.com/w3c/webextensions/issues/517): sidePanel API: lifecycle events
   * [Issue 520](https://github.com/w3c/webextensions/issues/520): Increase maximum total size (QUOTA_BYTES) for storage.sync
   * [Issue 521](https://github.com/w3c/webextensions/issues/521): sidePanel API: sidePanel.close() and sidePanel.toggle()
   * [Issue 522](https://github.com/w3c/webextensions/issues/522): Proposal: Give extensions easy access to MediaSession
   * [Issue 523](https://github.com/w3c/webextensions/issues/523): API limitation: content scripts URL matches and History API, Navigation API, BFCache
   * [Issue 527](https://github.com/w3c/webextensions/issues/527): chrome.scripting.executeScript doesn't resolve/reject for frozen state tabs
   * [Issue 528](https://github.com/w3c/webextensions/issues/528): Inconsistency: chrome.downloads.open() return value
   * [Issue 533](https://github.com/w3c/webextensions/issues/533): Enhance browser.storage.local to allow storing binary data directly
   * [Issue 534](https://github.com/w3c/webextensions/issues/534): Inconsistency with indexedDB in browser extensions

**Comment by oliverdunk** [comment] 2024-02-08 10:21
I'd like to nominate https://github.com/w3c/webextensions/pull/540 for the timely issues since we are looking to implement it in response to feedback on the `browser.userScripts` API.

**Comment by ghostwords** [comment] 2024-02-08 15:46
#302 is still an unsolved regression in Manifest V3. It is troubling to see [official Chrome docs](https://developer.chrome.com/docs/extensions/develop/migrate/known-issues ) claim "There are currently no open issues considered a critical platform gap".

**Comment by patrickkettner** [comment] 2024-02-08 15:57
@ghostwords it is not considered critical - as it a platform stopping feature. I believe it is very important, but it is used by an extraordinarily small amount of extensions. It _is_ a bug, and it is being actively worked on. https://issues.chromium.org/issues/40727004 is the over all work. The first pieces already landed, and the feature should be shipping in the near future.

**Comment by ghostwords** [comment] 2024-02-08 16:27
>used by an extraordinarily small amount of extensions

??? This is used by Privacy Badger, probably uBlock Origin, and the entire category of link cleaning extensions.

From https://github.com/w3c/webextensions/issues/302#issuecomment-1366010014

>Many [other extensions (list dated 2018)](https://github.com/Cimbali/CleanLinks/issues/20#issuecomment-395927561) rely on the same mechanisms.

**Comment by tophf** [comment] 2024-02-08 16:41
> extraordinarily small amount of extensions

Used by tens of millions of people if not more. Unless your team starts to challenge these weird ideas that you regularly propagate, there'll be a catastrophe when MV2 is finally removed in Chrome with no way to re-enable it.

> https://issues.chromium.org/issues/40727004 is the over all work

No, it's about a different specific problem, not related to #302. There are many such issues with no solution in ManifestV3. If you're a devrel where "dev" refers to us you might want to revisit all these reports here in WECG and in crbug.

**Comment by bershanskiy** [comment] 2024-02-12 11:18
I'd like to nominate the following issues for timely consideration:
 - #454
    - We have a concrete API proposal
    - Chromium Canary already ships with parsing code for this key, would be nice to have a spec and ship this feature in Chromium Beta 123 or 124
 - #401 
    - We have a concrete API proposal with a few stylistic ambiguities
    - I have an implementation locally which I haven't submitted for CL just waiting for API proposal finalization
 - #433
    - We determined timer delay after suspend to be a bug
    - We fixed it in Chromium 123 ([source](https://chromiumdash.appspot.com/commit/2c34dfa35bbf78d31da9addfcf9ab3c27e4f8411))
    - Firefox still has this delay
    - Safari never had this delay
    - We should probably make sure we are on the same page and close the issue right away

**Comment by dotproto** [comment] 2024-02-15 15:36
Closing this issue in preparation for today's meeting.

**Closed as completed by dotproto** 2024-02-15 15:36 UTC
Labels: agenda
